//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestResult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppRun
    {
        public AppRun()
        {
            this.TestSuiteRuns = new HashSet<TestSuiteRun>();
        }
    
        public int AppRunId { get; set; }
        public string AppArea { get; set; }
        public System.DateTime BuildDate { get; set; }
        public string ServerName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Alias { get; set; }
        public string DbType { get; set; }
    
        public virtual ICollection<TestSuiteRun> TestSuiteRuns { get; set; }
    }
}
