//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestResult.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnitTestLogEntities : DbContext
    {
        public UnitTestLogEntities()
            : base("name=UnitTestLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppRun> AppRuns { get; set; }
        public DbSet<TestCaseRun> TestCaseRuns { get; set; }
        public DbSet<TestError> TestErrors { get; set; }
        public DbSet<TestSuiteRun> TestSuiteRuns { get; set; }
    }
}
