//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestResult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSuiteRun
    {
        public TestSuiteRun()
        {
            this.TestCaseRuns = new HashSet<TestCaseRun>();
        }
    
        public int SuiteRunId { get; set; }
        public Nullable<int> AppRunId { get; set; }
        public string Name { get; set; }
        public double Duration { get; set; }
    
        internal virtual AppRun AppRun { get; set; }
        public virtual ICollection<TestCaseRun> TestCaseRuns { get; set; }
    }
}
