//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestResult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCaseRun
    {
        public TestCaseRun()
        {
            this.TestErrors = new HashSet<TestError>();
        }
    
        public int CaseRunId { get; set; }
        public Nullable<int> SuiteRunId { get; set; }
        public string Name { get; set; }
        public double Duration { get; set; }
    
        internal virtual TestSuiteRun TestSuiteRun { get; set; }
        public virtual ICollection<TestError> TestErrors { get; set; }
    }
}
