//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestResult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestError
    {
        public int ErrorId { get; set; }
        public Nullable<int> CaseRunId { get; set; }
        public string Message { get; set; }
    
        internal virtual TestCaseRun TestCaseRun { get; set; }
    }
}
